### ISSUE TITLE
"hide-nitro-upselling.theme.css" doesn't hide the superreaction button

### ISSUE THREAD

**Issue by GTREDITION** [D3SOX/complementary-discord-theme#1]
![imagen](https://github.com/D3SOX/complementary-discord-theme/assets/53015599/3cb10415-5618-4835-aaa9-cd82063bb203)

**Comment by D3SOX** [comment]
I think my selector only works if Discord is set to US English. Otherwise if it still happens I might need to take a look if Discord changed something when I'm back home
